
spring:
  application:
    name: company-staff-manage #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/csm?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 'wensong'
    dbcp2:
      min-idle: 5                         # 数据库连接池的最小维持连接数
      initial-size: 5                     # 初始化连接数
      max-total: 5                        # 最大连接数
      max-wait-millis: 150                # 等待连接获取的最大超时时间